nodeLinker: 'pnp'
enableScripts: false
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-static-node-gyp-build.js
    spec: .yarn/plugins/@yarnpkg/plugin-static-node-gyp-build.js
  - path: .yarn/plugins/@yarnpkg/plugin-redirect-app-builder.js
    spec: 'https://raw.githubusercontent.com/electricui/yarn-redirect-app-builder/master/bundles/%40yarnpkg/plugin-redirect-app-builder.js'
npmScopes:
  electricui:
    npmRegistryServer: 'https://registry.eui.io/'
packageExtensions:
  debug@*:
    dependencies:
      supports-color: 7.1.0

logFilters:
  - code: 'YN0004'
    level: discard
